######################################################################
# Automatically generated by qmake (1.07a) Fri Jul 1 13:02:36 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += DisplayList.hpp \
           DrawingShapes.hpp \
           FillStyles.hpp \
           functions.h \
           LineStyles.hpp \
           MovieBasics.hpp \
           Transforms.hpp
SOURCES += functions.cpp main.cpp
