#############################################################################
# Makefile for building: f4l
# Generated by qmake (2.01a) (Qt 4.6.3) on: Sat Mar 26 10:51:18 2011
# Project:  f4l.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o Makefile f4l.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src-flagStonePort-transform-cxx-bsd-transform \
		sub-src-flagStonePort-transform-util-cxx-transform-util \
		sub-src

src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/flagStonePort/transform-cxx-bsd/transform/ || $(MKDIR) src/flagStonePort/transform-cxx-bsd/transform/ 
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(QMAKE) /home/mascix/Projects/f4l/src/flagStonePort/transform-cxx-bsd/transform/transform.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o $(MAKEFILE)
sub-src-flagStonePort-transform-cxx-bsd-transform-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/flagStonePort/transform-cxx-bsd/transform/ || $(MKDIR) src/flagStonePort/transform-cxx-bsd/transform/ 
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(QMAKE) /home/mascix/Projects/f4l/src/flagStonePort/transform-cxx-bsd/transform/transform.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o $(MAKEFILE)
sub-src-flagStonePort-transform-cxx-bsd-transform: src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) -f $(MAKEFILE)
sub-src-flagStonePort-transform-cxx-bsd-transform-make_default: src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) -f $(MAKEFILE) 
sub-src-flagStonePort-transform-cxx-bsd-transform-make_first: src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) -f $(MAKEFILE) first
sub-src-flagStonePort-transform-cxx-bsd-transform-all: src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) -f $(MAKEFILE) all
sub-src-flagStonePort-transform-cxx-bsd-transform-clean: src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-flagStonePort-transform-cxx-bsd-transform-distclean: src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-flagStonePort-transform-cxx-bsd-transform-install_subtargets: src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) -f $(MAKEFILE) install
sub-src-flagStonePort-transform-cxx-bsd-transform-uninstall_subtargets: src/flagStonePort/transform-cxx-bsd/transform//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) -f $(MAKEFILE) uninstall
src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/flagStonePort/transform-util-cxx/transform-util/ || $(MKDIR) src/flagStonePort/transform-util-cxx/transform-util/ 
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(QMAKE) /home/mascix/Projects/f4l/src/flagStonePort/transform-util-cxx/transform-util/transform-util.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o $(MAKEFILE)
sub-src-flagStonePort-transform-util-cxx-transform-util-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/flagStonePort/transform-util-cxx/transform-util/ || $(MKDIR) src/flagStonePort/transform-util-cxx/transform-util/ 
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(QMAKE) /home/mascix/Projects/f4l/src/flagStonePort/transform-util-cxx/transform-util/transform-util.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o $(MAKEFILE)
sub-src-flagStonePort-transform-util-cxx-transform-util: src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) -f $(MAKEFILE)
sub-src-flagStonePort-transform-util-cxx-transform-util-make_default: src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) -f $(MAKEFILE) 
sub-src-flagStonePort-transform-util-cxx-transform-util-make_first: src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) -f $(MAKEFILE) first
sub-src-flagStonePort-transform-util-cxx-transform-util-all: src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) -f $(MAKEFILE) all
sub-src-flagStonePort-transform-util-cxx-transform-util-clean: src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-flagStonePort-transform-util-cxx-transform-util-distclean: src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-flagStonePort-transform-util-cxx-transform-util-install_subtargets: src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) -f $(MAKEFILE) install
sub-src-flagStonePort-transform-util-cxx-transform-util-uninstall_subtargets: src/flagStonePort/transform-util-cxx/transform-util//$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) -f $(MAKEFILE) uninstall
src//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/mascix/Projects/f4l/src/src.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/mascix/Projects/f4l/src/src.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o $(MAKEFILE)
sub-src: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: f4l.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/debug_and_release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o Makefile f4l.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/debug_and_release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug_and_release CONFIG+=debug -o Makefile f4l.pro

qmake_all: sub-src-flagStonePort-transform-cxx-bsd-transform-qmake_all sub-src-flagStonePort-transform-util-cxx-transform-util-qmake_all sub-src-qmake_all FORCE

make_default: sub-src-flagStonePort-transform-cxx-bsd-transform-make_default sub-src-flagStonePort-transform-util-cxx-transform-util-make_default sub-src-make_default FORCE
make_first: sub-src-flagStonePort-transform-cxx-bsd-transform-make_first sub-src-flagStonePort-transform-util-cxx-transform-util-make_first sub-src-make_first FORCE
all: sub-src-flagStonePort-transform-cxx-bsd-transform-all sub-src-flagStonePort-transform-util-cxx-transform-util-all sub-src-all FORCE
clean: sub-src-flagStonePort-transform-cxx-bsd-transform-clean sub-src-flagStonePort-transform-util-cxx-transform-util-clean sub-src-clean FORCE
distclean: sub-src-flagStonePort-transform-cxx-bsd-transform-distclean sub-src-flagStonePort-transform-util-cxx-transform-util-distclean sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-flagStonePort-transform-cxx-bsd-transform-install_subtargets sub-src-flagStonePort-transform-util-cxx-transform-util-install_subtargets sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-flagStonePort-transform-cxx-bsd-transform-uninstall_subtargets sub-src-flagStonePort-transform-util-cxx-transform-util-uninstall_subtargets sub-src-uninstall_subtargets FORCE

sub-src-flagStonePort-transform-cxx-bsd-transform-sub_Debug: src/flagStonePort/transform-cxx-bsd/transform/$(MAKEFILE)
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) debug
sub-src-flagStonePort-transform-util-cxx-transform-util-sub_Debug: src/flagStonePort/transform-util-cxx/transform-util/$(MAKEFILE)
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) debug
sub-src-sub_Debug: src/$(MAKEFILE)
	cd src/ && $(MAKE) debug
debug: sub-src-flagStonePort-transform-cxx-bsd-transform-sub_Debug sub-src-flagStonePort-transform-util-cxx-transform-util-sub_Debug sub-src-sub_Debug

sub-src-flagStonePort-transform-cxx-bsd-transform-sub_Release: src/flagStonePort/transform-cxx-bsd/transform/$(MAKEFILE)
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) release
sub-src-flagStonePort-transform-util-cxx-transform-util-sub_Release: src/flagStonePort/transform-util-cxx/transform-util/$(MAKEFILE)
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) release
sub-src-sub_Release: src/$(MAKEFILE)
	cd src/ && $(MAKE) release
release: sub-src-flagStonePort-transform-cxx-bsd-transform-sub_Release sub-src-flagStonePort-transform-util-cxx-transform-util-sub_Release sub-src-sub_Release

sub-src-flagStonePort-transform-cxx-bsd-transform-check: src/flagStonePort/transform-cxx-bsd/transform/$(MAKEFILE)
	cd src/flagStonePort/transform-cxx-bsd/transform/ && $(MAKE) check
sub-src-flagStonePort-transform-util-cxx-transform-util-check: src/flagStonePort/transform-util-cxx/transform-util/$(MAKEFILE)
	cd src/flagStonePort/transform-util-cxx/transform-util/ && $(MAKE) check
sub-src-check: src/$(MAKEFILE)
	cd src/ && $(MAKE) check
check: sub-src-flagStonePort-transform-cxx-bsd-transform-check sub-src-flagStonePort-transform-util-cxx-transform-util-check sub-src-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

