#############################################################################
# Makefile for building: f4l
# Generated by qmake (1.07a) (Qt 3.3.4) on: Sun Nov 13 16:34:49 2005
# Project:  f4l.pro
# Template: subdirs
# Command: $(QMAKE) -o Makefile f4l.pro
#############################################################################

MAKEFILE =	Makefile
QMAKE    =	qmake
DEL_FILE =    rm -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p
INSTALL_FILE= 
INSTALL_DIR = 
SUBTARGETS =	 \
		sub-src-flagStonePort-transform-cxx-bsd-transform \
		sub-src-flagStonePort-transform-util-cxx-transform-util \
		sub-src

first: all

all: Makefile $(SUBTARGETS)

src/flagStonePort/transform-cxx-bsd/transform/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/flagStonePort/transform-cxx-bsd/transform" || $(MKDIR) "src/flagStonePort/transform-cxx-bsd/transform"
	cd src/flagStonePort/transform-cxx-bsd/transform && $(QMAKE) transform.pro -o $(MAKEFILE)
sub-src-flagStonePort-transform-cxx-bsd-transform: src/flagStonePort/transform-cxx-bsd/transform/$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-cxx-bsd/transform && $(MAKE) -f $(MAKEFILE)

src/flagStonePort/transform-util-cxx/transform-util/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/flagStonePort/transform-util-cxx/transform-util" || $(MKDIR) "src/flagStonePort/transform-util-cxx/transform-util"
	cd src/flagStonePort/transform-util-cxx/transform-util && $(QMAKE) transform-util.pro -o $(MAKEFILE)
sub-src-flagStonePort-transform-util-cxx-transform-util: src/flagStonePort/transform-util-cxx/transform-util/$(MAKEFILE) FORCE
	cd src/flagStonePort/transform-util-cxx/transform-util && $(MAKE) -f $(MAKEFILE)

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src" || $(MKDIR) "src"
	cd src && $(QMAKE) src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE)

Makefile: f4l.pro  /usr/share/qt3/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile f4l.pro
qmake: qmake_all
	@$(QMAKE) -o Makefile f4l.pro

all: $(SUBTARGETS)
qmake_all: src/flagStonePort/transform-cxx-bsd/transform/$(MAKEFILE) src/flagStonePort/transform-util-cxx/transform-util/$(MAKEFILE) src/$(MAKEFILE)
	 ( [ -d src/flagStonePort/transform-cxx-bsd/transform ] && cd src/flagStonePort/transform-cxx-bsd/transform ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
	 ( [ -d src/flagStonePort/transform-util-cxx/transform-util ] && cd src/flagStonePort/transform-util-cxx/transform-util ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
	 ( [ -d src ] && cd src ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
clean uicables mocables uiclean mocclean lexclean yaccclean : qmake_all FORCE
	 ( [ -d src/flagStonePort/transform-cxx-bsd/transform ] && cd src/flagStonePort/transform-cxx-bsd/transform ; $(MAKE) -f $(MAKEFILE) $@; ) || true
	 ( [ -d src/flagStonePort/transform-util-cxx/transform-util ] && cd src/flagStonePort/transform-util-cxx/transform-util ; $(MAKE) -f $(MAKEFILE) $@; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) $@; ) || true
uninstall_subdirs: qmake_all FORCE
	 ( [ -d src/flagStonePort/transform-cxx-bsd/transform ] && cd src/flagStonePort/transform-cxx-bsd/transform ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
	 ( [ -d src/flagStonePort/transform-util-cxx/transform-util ] && cd src/flagStonePort/transform-util-cxx/transform-util ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
install_subdirs: qmake_all FORCE
	 ( [ -d src/flagStonePort/transform-cxx-bsd/transform ] && cd src/flagStonePort/transform-cxx-bsd/transform ; $(MAKE) -f $(MAKEFILE) install; ) || true
	 ( [ -d src/flagStonePort/transform-util-cxx/transform-util ] && cd src/flagStonePort/transform-util-cxx/transform-util ; $(MAKE) -f $(MAKEFILE) install; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) install; ) || true
distclean: qmake_all FORCE
	 ( [ -d src/flagStonePort/transform-cxx-bsd/transform ] && cd src/flagStonePort/transform-cxx-bsd/transform ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true
	 ( [ -d src/flagStonePort/transform-util-cxx/transform-util ] && cd src/flagStonePort/transform-util-cxx/transform-util ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true

install:  install_subdirs

uninstall:  uninstall_subdirs

FORCE:

